<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
    <?php
    $link = $_SERVER['REQUEST_URI'];
    switch ($link) {
        case '/FP_DWO_KELOMPOK_11/index.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/fact_sales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/fact_purchasing.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/customer.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/employee.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/product.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/sales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link active">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/shipping.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/vendor.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/dwsales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item menu-is-opening menu-open">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link active">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/dwpurchasing.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item menu-is-opening menu-open">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link active">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/dwshipsales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item menu-is-opening menu-open">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link active">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/dwshippurchase.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item menu-is-opening menu-open">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link active">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
        default:
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-money-bill-wave"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shopping-cart"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-users"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-people-carry"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-box"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon ion ion-person-add"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-shipping-fast"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-industry"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="#" class="nav-link">';
            echo '<i class="nav-icon fas fa-database"></i>';
            echo '<p>';
            echo 'OLAP';
            echo '<i class="right fas fa-angle-left"></i>';
            echo '</p>';
            echo '</a>';
            echo '<ul class="nav nav-treeview">';
            echo '<li class="nav-item">';
            echo '<a href="dwsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwpurchasing.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshipsales.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Sales</p>';
            echo '</a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="dwshippurchase.php" class="nav-link">';
            echo '<i class="far fa-circle nav-icon"></i>';
            echo '<p>Data Warehouse Ship Purchasing</p>';
            echo '</a>';
            echo '</li>';
            echo '</ul>';
            echo '</li>';
            break;
    }
    ?>
</ul>